"""Secure execution kernel.

Products may replace the exported strategy protocols, but every ToolIntent must
still pass through :class:`ExecutionRunner` and its root-owned dependencies.
"""

from suiteharness.execution.in_memory import (
    InMemoryApprovalStore,
    InMemoryAuditJournal,
    InMemoryCapabilityAuthority,
    InMemoryToolRegistry,
    ToolRegistrationHandle,
)
from suiteharness.execution.models import (
    ApprovalBinding,
    ApprovalCredential,
    ApprovalTarget,
    AuditEvent,
    AuditEventType,
    CapabilityGrant,
    ConversationContext,
    ConversationMessage,
    ExecutionBudget,
    FailureCode,
    PromptEnvelope,
    PromptMessage,
    RunFailure,
    RunRequest,
    RunResult,
    RunStatus,
    ToolAuthorization,
    ToolCallStatus,
    ToolEffect,
    ToolIdentity,
    ToolIntent,
    ToolObservation,
    ToolSpec,
    WorkflowDecision,
    WorkflowDecisionKind,
    WorkflowFrame,
    arguments_digest,
)
from suiteharness.execution.protocols import (
    PROMPT_STRATEGY,
    REFLECTION_STRATEGY,
    WORKFLOW,
    ApprovalStore,
    AuditJournal,
    CapabilityAuthority,
    ExecutionStrategies,
    InteractiveApprovalBroker,
    PromptStrategy,
    ReflectionStrategy,
    RegisteredTool,
    ToolAuthorizationPolicy,
    ToolCallContext,
    ToolHandler,
    ToolInputValidator,
    ToolRegistry,
    Workflow,
)
from suiteharness.execution.runner import ExecutionPolicy, ExecutionRunner
from suiteharness.execution.sqlite import AuditConflictError, SQLiteAuditJournal

__all__ = [
    "PROMPT_STRATEGY",
    "REFLECTION_STRATEGY",
    "WORKFLOW",
    "ApprovalBinding",
    "ApprovalCredential",
    "ApprovalTarget",
    "AuditConflictError",
    "ApprovalStore",
    "AuditEvent",
    "AuditEventType",
    "AuditJournal",
    "CapabilityAuthority",
    "CapabilityGrant",
    "ConversationContext",
    "ConversationMessage",
    "ExecutionBudget",
    "ExecutionPolicy",
    "ExecutionRunner",
    "ExecutionStrategies",
    "FailureCode",
    "InMemoryApprovalStore",
    "InMemoryAuditJournal",
    "InMemoryCapabilityAuthority",
    "InMemoryToolRegistry",
    "InteractiveApprovalBroker",
    "PromptEnvelope",
    "PromptMessage",
    "PromptStrategy",
    "ReflectionStrategy",
    "RegisteredTool",
    "RunFailure",
    "RunRequest",
    "RunResult",
    "RunStatus",
    "SQLiteAuditJournal",
    "ToolCallContext",
    "ToolCallStatus",
    "ToolAuthorization",
    "ToolEffect",
    "ToolHandler",
    "ToolIdentity",
    "ToolInputValidator",
    "ToolIntent",
    "ToolObservation",
    "ToolRegistry",
    "ToolAuthorizationPolicy",
    "ToolRegistrationHandle",
    "ToolSpec",
    "Workflow",
    "WorkflowDecision",
    "WorkflowDecisionKind",
    "WorkflowFrame",
    "arguments_digest",
]
