"""Secure source-deployment plugin discovery and transactional lifecycle."""

from suiteharness.plugins.discovery import (
    AllowlistedTrustPolicy,
    PluginDiscovery,
    SignatureVerifier,
    TrustPolicy,
    VerifiedPluginSource,
    deterministic_directory_digest,
    signature_payload,
)
from suiteharness.plugins.errors import (
    PluginDiscoveryError,
    PluginError,
    PluginErrorCode,
    PluginLifecycleError,
    PluginPlanError,
)
from suiteharness.plugins.graph import PluginPlan, PluginPlanner, ResolvedRequirement
from suiteharness.plugins.lifecycle import (
    CleanupFailure,
    FiberState,
    PluginCleanupError,
    PluginFiber,
)
from suiteharness.plugins.loader import PythonEntrypointLoader
from suiteharness.plugins.manager import (
    PluginActivationContext,
    PluginManager,
    PluginPrepareContext,
)
from suiteharness.plugins.models import (
    PLUGIN_SCHEMA_VERSION,
    ArtifactIntegrity,
    ContributionDeclaration,
    ContributionKind,
    Contributions,
    Permission,
    PermissionSet,
    PluginManifest,
    PluginSourceDeclaration,
    ProvidedService,
    RequiredService,
    SignatureMetadata,
    TrustMode,
)
from suiteharness.plugins.protocols import (
    ContributionHandle,
    ContributionRegistration,
    ContributionRegistry,
    PluginActivationContextProtocol,
    PluginActivationIdentity,
    PluginLaunchDescriptor,
    PluginLauncher,
    PluginPrepareContextProtocol,
    PluginRuntime,
    PreparedPlugin,
    ProviderBinding,
    TrustedPluginLoader,
)
from suiteharness.plugins.registry import (
    InMemoryContributionRegistry,
    VisibleContribution,
)

__all__ = [
    "AllowlistedTrustPolicy",
    "ArtifactIntegrity",
    "CleanupFailure",
    "ContributionDeclaration",
    "ContributionHandle",
    "ContributionKind",
    "ContributionRegistration",
    "ContributionRegistry",
    "Contributions",
    "FiberState",
    "InMemoryContributionRegistry",
    "PLUGIN_SCHEMA_VERSION",
    "Permission",
    "PermissionSet",
    "PluginActivationContext",
    "PluginActivationContextProtocol",
    "PluginActivationIdentity",
    "PluginCleanupError",
    "PluginDiscovery",
    "PluginDiscoveryError",
    "PluginError",
    "PluginErrorCode",
    "PluginFiber",
    "PluginLaunchDescriptor",
    "PluginLauncher",
    "PluginLifecycleError",
    "PluginManager",
    "PluginManifest",
    "PluginPlan",
    "PluginPlanError",
    "PluginPlanner",
    "PluginPrepareContext",
    "PluginPrepareContextProtocol",
    "PluginRuntime",
    "PluginSourceDeclaration",
    "PreparedPlugin",
    "ProvidedService",
    "ProviderBinding",
    "PythonEntrypointLoader",
    "RequiredService",
    "ResolvedRequirement",
    "SignatureMetadata",
    "SignatureVerifier",
    "TrustMode",
    "TrustPolicy",
    "TrustedPluginLoader",
    "VerifiedPluginSource",
    "VisibleContribution",
    "deterministic_directory_digest",
    "signature_payload",
]
