"""Provider-neutral model gateway and server-credential adapters."""

from suiteharness.models.adapters import (
    AnthropicMessagesAdapter,
    BedrockConverseAdapter,
    BedrockRuntimeClient,
    Boto3BedrockRuntimeClient,
    GeminiAdapter,
    GoogleAuthTokenProvider,
    OpenAIChatAdapter,
    OpenAIResponsesAdapter,
    VertexGeminiAdapter,
    bedrock_factory,
    vertex_factory,
)
from suiteharness.models.errors import ModelErrorCode, ModelProviderError
from suiteharness.models.gateway import ModelGateway
from suiteharness.models.protocols import AccessTokenProvider, ModelProvider, SecretResolver
from suiteharness.models.registry import (
    BUILTIN_PROVIDERS,
    ProviderFactory,
    ProviderRegistry,
    create_builtin_provider_registry,
)
from suiteharness.models.secrets import MappingSecretResolver
from suiteharness.models.transport import (
    HttpRequest,
    HttpResponse,
    HttpTransport,
    HttpxTransport,
    iter_sse_json,
)
from suiteharness.models.types import (
    AdapterKind,
    ContentPart,
    DocumentContent,
    FinishReason,
    ImageContent,
    ModelMessage,
    ModelProfile,
    ModelRequest,
    ModelResponse,
    ModelRole,
    ModelRoute,
    ModelStreamEvent,
    ModelStreamEventType,
    ModelTool,
    ModelToolCall,
    ModelUsage,
    ProviderAuthKind,
    ProviderCapabilities,
    ProviderDescriptor,
    TextContent,
)

__all__ = [
    "BUILTIN_PROVIDERS",
    "AccessTokenProvider",
    "AdapterKind",
    "AnthropicMessagesAdapter",
    "BedrockConverseAdapter",
    "BedrockRuntimeClient",
    "Boto3BedrockRuntimeClient",
    "bedrock_factory",
    "ContentPart",
    "DocumentContent",
    "FinishReason",
    "GeminiAdapter",
    "GoogleAuthTokenProvider",
    "HttpRequest",
    "HttpResponse",
    "HttpTransport",
    "HttpxTransport",
    "ImageContent",
    "MappingSecretResolver",
    "ModelErrorCode",
    "ModelGateway",
    "ModelMessage",
    "ModelProfile",
    "ModelProvider",
    "ModelProviderError",
    "ModelRequest",
    "ModelResponse",
    "ModelRole",
    "ModelRoute",
    "ModelStreamEvent",
    "ModelStreamEventType",
    "ModelTool",
    "ModelToolCall",
    "ModelUsage",
    "OpenAIChatAdapter",
    "OpenAIResponsesAdapter",
    "ProviderAuthKind",
    "ProviderCapabilities",
    "ProviderDescriptor",
    "ProviderFactory",
    "ProviderRegistry",
    "SecretResolver",
    "TextContent",
    "VertexGeminiAdapter",
    "vertex_factory",
    "create_builtin_provider_registry",
    "iter_sse_json",
]
