"""Memory capabilities: isolated private profiles and curated Customer360 sharing."""

from .errors import MemoryCapabilityError, MemoryErrorCode
from .in_memory import (
    InMemoryCustomer360Provider,
    InMemoryProfileDirectory,
    InMemoryProfileProvider,
)
from .knowledge import InMemoryKnowledgeProvider
from .models import (
    CURATOR,
    ENTITY_ADMIN,
    KNOWLEDGE_READ,
    KNOWLEDGE_WRITE,
    PRIVATE_READ,
    PRIVATE_WRITE,
    SHARE_PROPOSE,
    SHARED_READ,
    SHARING_ADMIN,
    CandidateStatus,
    CurationAction,
    CurationDecision,
    CurationResult,
    EntityAlias,
    EntityRevision,
    EvidenceRecord,
    KnowledgeDocument,
    KnowledgeHit,
    PeerPredicateRule,
    PrivateClaim,
    PrivateClaimStatus,
    ProvenanceRef,
    RequestScope,
    ShareCandidate,
    SharedClaim,
    SharedClaimStatus,
    SharingPolicy,
    SpaceKind,
    SpaceRef,
    WithdrawalReceipt,
)
from .protocols import (
    Customer360Provider,
    EvidenceProvider,
    KnowledgeProvider,
    ProfileProvider,
    ProfileProviderResolver,
)
from .services import (
    CUSTOMER360_PROVIDER,
    EVIDENCE_PROVIDER,
    KNOWLEDGE_PROVIDER,
    PROFILE_PROVIDER,
)

__all__ = [
    "CURATOR",
    "CUSTOMER360_PROVIDER",
    "ENTITY_ADMIN",
    "PRIVATE_READ",
    "PRIVATE_WRITE",
    "SHARE_PROPOSE",
    "SHARED_READ",
    "SHARING_ADMIN",
    "CandidateStatus",
    "CurationAction",
    "CurationDecision",
    "CurationResult",
    "Customer360Provider",
    "EntityAlias",
    "EntityRevision",
    "EvidenceProvider",
    "EVIDENCE_PROVIDER",
    "EvidenceRecord",
    "InMemoryCustomer360Provider",
    "InMemoryKnowledgeProvider",
    "InMemoryProfileDirectory",
    "InMemoryProfileProvider",
    "KnowledgeDocument",
    "KnowledgeHit",
    "KNOWLEDGE_READ",
    "KNOWLEDGE_WRITE",
    "KnowledgeProvider",
    "KNOWLEDGE_PROVIDER",
    "MemoryCapabilityError",
    "MemoryErrorCode",
    "PeerPredicateRule",
    "PrivateClaim",
    "PrivateClaimStatus",
    "PROFILE_PROVIDER",
    "ProfileProvider",
    "ProfileProviderResolver",
    "ProvenanceRef",
    "RequestScope",
    "ShareCandidate",
    "SharedClaim",
    "SharedClaimStatus",
    "SharingPolicy",
    "SpaceKind",
    "SpaceRef",
    "WithdrawalReceipt",
]
